language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtest-dev libgtest0 zlib1g zlib1g-dev
script: ./autogen.sh && ./configure --enable-gtest && make
