language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libgtest-dev zlibc zlib1g zlib1g-dev libtool libsnappy-dev lcov
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo mv config/gtest-config /usr/bin
  - cd $(mktemp -d)
  - cmake /usr/src/gtest
  - make
  - sudo mv libgtest.a /usr/lib/
  - sudo mv libgtest_main.a /usr/lib
  - cd $TRAVIS_BUILD_DIR
script:
  - ./autogen.sh && ./configure --enable-gcov && make && make check && make coverage-html && make distcheck
after_success:
  - coveralls --no-gcov --exclude lib --exclude tests --verbose
