language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libgtest-dev zlibc zlib1g zlib1g-dev libtool
  - sudo mv config/gtest-config /usr/bin
  - cd $(mktemp -d)
  - cmake /usr/src/gtest
  - make
  - sudo mv libgtest.a /usr/lib/
  - sudo mv libgtest_main.a /usr/lib
  - cd $TRAVIS_BUILD_DIR
script: ./autogen.sh && ./configure --enable-gtest && make && make check && DISTCHECK_CONFIGURE_FLAGS=--enable-gtest make distcheck
